SmollProdject/urls.py
from django.contrib import admin
from django.urls import path, include
from listings.views import listings_view
from main_app.views import main_view
from django.conf import settings
from django.conf.urls.static import static
from account.views import registration_view, login_view, logout_view
from office.views import office_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listings/', listings_view, name='listings'),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),
    path('office/', office_view, name='office'),
    path('', main_view, name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation

app_name = 'manager'

urlpatterns = [
	path('', reservation_list, name='reservation'),
	path('update/<int:pk>', update_reservation, name='update_reservation'),
]

main_app/models.py
from django.db import models
from django.core.validators import RegexValidator


# Create your models here.
class ProductCutegory(models.Model):
    title = models.CharField(max_length=100, unique=True)
    position = models.PositiveSmallIntegerField(unique=True)
    is_visible = models.BooleanField(default=True)

    def __iter__(self):
        for i in self.products.all():
            yield i

    def __str__(self) -> str:
        return f"{self.title}"

    class Meta:
        ordering = ("position",)


class Products(models.Model):
    title = models.CharField(max_length=100, unique=True)
    position = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True)
    is_cpecial = models.BooleanField(default=True)
    is_signature = models.BooleanField(default=True)
    categories = models.ForeignKey(ProductCutegory, on_delete=models.CASCADE, related_name="products")
    disc = models.TextField(max_length=200, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    width = models.CharField(max_length=100)
    height = models.CharField(max_length=100)
    length = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="products")

    def total_price(self):
        return self.price - self.discount / 100 * self.price

    def __str__(self) -> str:
        return f"{self.title}"

    class Meta:
        ordering = ("position",)


class Agents(models.Model):
    title = models.CharField(max_length=100)
    position = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True)
    disc = models.TextField(max_length=200, blank=True)
    photo = models.ImageField(upload_to="products")

    def __str__(self) -> str:
        return f"{self.title}"

    class Meta:
        ordering = ("position",)


class Reservation(models.Model):
    phone_validator = RegexValidator(
        regex="^\+?3?8?0?\d{2}[ -]?(\d[ -]?){7}$",
        message="the number should have the following format: +380xx xxx xx xx",
    )
    email_validator = RegexValidator(regex="^\w+(_?\w*)*-?\w*(_?\w*)*@\w+(\.\w*)+$", message="xxxxxx@xxxxxx")
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, validators=(email_validator,))
    phone = models.CharField(max_length=16, validators=(phone_validator,))
    date_request = models.DateTimeField(auto_now_add=True)
    date_response = models.DateTimeField(auto_now=True)
    message = models.TextField(max_length=1000, blank=True)
    is_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ("-date_response",)

    def __str__(self):
        return f"{self.name}\t{self.phone}\t{self.email}"


class New(models.Model):
    title = models.CharField(max_length=100, unique=True)
    photo = models.ImageField(upload_to="dishes")
    is_visible = models.BooleanField(default=True)
    date = models.DateField()
    time = models.TimeField()
    message = models.TextField(max_length=1000, blank=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        ordering = ("date",)

main_app/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('name', 'email', 'phone', 'message')

    name = forms.CharField(max_length=100, widget=forms.TextInput(
            attrs={'class': "form-control", 'type': "text", 'id': "fname", 'placeholder': "ім'я"}))

    email = forms.EmailField(widget=forms.TextInput(
            attrs={'type': "email", 'class': "form-control", 'id': "exampleInputEmail1", 'placeholder': "Ваш email"}))

    phone = forms.CharField(max_length=16, widget=forms.TextInput(
            attrs={'type': "subject", 'id': "subject", 'class': "form-control", 'aria-describedby': "phoneHelp",
                   'placeholder': "Ваш телефон"}))

    message = forms.CharField(max_length=1000, required=None, widget=forms.Textarea(
            attrs={' name': "message", 'id': "message", 'cols': "30", 'rows': "7", 'class': "form-control",
                   'placeholder': "Напишіть свої коментарі або запитання тут...", }))

main_app/views.py
from django.shortcuts import render, redirect
from .models import ProductCutegory, Products, Agents, New
from .forms import ReservationForm


# Create your views here.
def main_view(request):

    if request.method == 'POST':
        form_reserve = ReservationForm(request.POST)
        if form_reserve.is_valid():
            form_reserve.save()
            return redirect('/#')

    categories = ProductCutegory.objects.filter(is_visible=True)
    products = Products.objects.filter(is_visible=True, is_cpecial=True, is_signature=True)
    agents = Agents.objects.filter(is_visible=True)
    news = New.objects.filter(is_visible=True)
    form_reserve = ReservationForm()
    return render(request, 'main_page.html', context={
            'categories': categories,
            'products': products,
            'agents': agents,
            'form_reserve': form_reserve,
            'news': news,
        },
    )

main_app/templates/about.html
<section class="site-section" id="about-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="owl-carousel slide-one-item-alt">
            {% for photo in products %}
            <img src="{{photo.photo.url}}" alt="Image{{ photo.title }}" class="img-fluid" />
            {% endfor %}
        </div>
        <div class="custom-direction">
          <a href="#" class="custom-prev">Попередня</a
          ><a href="#" class="custom-next">Наступна</a>
        </div>
      </div>
      <div class="col-lg-5 ml-auto">
        <h2 class="section-title mb-3">Про Найкращу Компанію У Своїй Справі</h2>
        <p class="lead">
          Наша компанія - це провідний виробник дерев'яних блоків з брусів, а також ми маємо багаторічний досвід в будівництві дерев'яних будинків та бесідок.
        </p>
        <p>
          Ми використовуємо тільки найкращі сировинні матеріали та професійне обладнання, щоб забезпечити високу якість нашої продукції та послуг.
          Ми прагнемо забезпечити наших клієнтів найкращими рішеннями та індивідуальним підходом до кожного проекту.
          Наші дерев'яні блоки та будівлі відрізняються високою міцністю та довговічністю, що робить їх ідеальним вибором для будівництва будь-якої споруди з використанням дерева.
        </p>

        <ul class="list-unstyled ul-check success">
          <li>Висока якість продукції</li>
          <li>Індивідуальний підхід до кожного клієнта</li>
          <li>Екологічність</li>
          <li>Досвідчені фахівці</li>
          <li>Надійність</li>
        </ul>

        <p><a href="#" class="btn btn-primary mr-2 mb-2">Дізнаймя більше</a></p>
      </div>
    </div>
  </div>
</section>

main_app/templates/agents.html
<section class="site-section border-bottom" id="agents-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-12">
        <h2 class="section-title mb-3  text-center">Персонал</h2>
        <p class="lead text-center">
            Наші робітники мають великий досвід у роботі з деревом, вони проходять постійне навчання та підвищення кваліфікації, щоб забезпечувати високу якість продукції та послуг. У нашій команді є конструктори, які допоможуть вам розробити проект будівництва будинку чи бесідки, враховуючи всі ваші побажання та вимоги. Ми також маємо спеціалістів з монтажу та встановлення, які забезпечать професійний монтаж і установку вашої продукції.
        </p>
      </div>
    </div>
    <div class="row">
        {% for agent in agents %}
            <div class="col-md-6 col-lg-4 mb-4">
        <div class="team-member">
          <figure>
            <ul class="social">
              <li>
                <a href="#"><span class="icon-facebook"></span></a>
              </li>
              <li>
                <a href="#"><span class="icon-twitter"></span></a>
              </li>
              <li>
                <a href="#"><span class="icon-linkedin"></span></a>
              </li>
              <li>
                <a href="#"><span class="icon-instagram"></span></a>
              </li>
            </ul>
            <img src="{{agent.photo.url}}" alt="foto {{ agent.title }}" class="img-fluid" />
          </figure>
          <div class="p-3">
            <h3 class="mb-2">{{ agent.title }}</h3>
            <span class="position">{{ agent.disc }}</span>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
  </div>
</section>

main_app/templates/contact.html
<section class="site-section bg-light bg-image" id="contact-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-12 text-center">
        <!-- <h3 class="section-sub-title">Get</h3> -->
        <h2 class="section-title mb-3">Зв'яжіться з нами</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7 mb-5">
        <form action="#" class="p-5 bg-white" method="post">
            {% csrf_token %}
          <h2 class="font-weight-bold mb-5 text-secondary">Заповніть форму</h2>

          <div class="row form-group">
            <div class="col-md-12 mb-3 mb-md-0">
              <label class="text-dark" for="fname">Ім'я</label>
              {{form_reserve.name }}
            </div>

          </div>

          <div class="form-group">
            <label class="text-dark" for="exampleInputEmail1">Email</label>
            {{ form_reserve.email }}
          </div>

          <div class="row form-group">
            <div class="col-md-12">
              <label class="text-dark" for="subject">Телефон</label>
              {{ form_reserve.phone }}
               <small id="phoneHelp" class="form-text text-muted">Формат введення: +380**-***-**-**</small>
            </div>
          </div>

          <div class="row form-group">
            <div class="col-md-12">
              <label class="text-dark" for="message">Повідомлення</label>
              {{ form_reserve.message }}
            </div>
          </div>

          <div class="row form-group">
            <div class="col-md-12">
              <input
                type="submit"
                value="Відправити повідомлення"
                class="btn btn-primary btn-md text-white"
              />
            </div>
          </div>
        </form>
      </div>
      <div class="col-md-5">
        <div class="p-4 mb-3 bg-white">
          <p class="mb-0 font-weight-bold">Адреса</p>
          <p class="mb-4">
            Україна, Володимир-Волинський р-н, м.Володимир
          </p>

          <p class="mb-0 font-weight-bold">Телефон</p>
          <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

          <p class="mb-0 font-weight-bold">Email Address</p>
          <p class="mb-0"><a href="#">youremail@domain.com</a></p>
        </div>
      </div>
    </div>
  </div>
</section>

main_app/templates/home_section.html
<div
  class="site-blocks-cover overlay"
  style="background-image: url(/static/img/property_5-sm.jpg)"
  data-aos="fade"
  id="home-section"
>
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-12 mt-lg-5 text-center">
        <h1>Будинки, бесідки та вироби з дерева.</h1>
        <br /><br />
        <p class="mb-12">
          Наша компанія спеціалізується на виготовленні дерев'яних блоків з
          брусів, а також будівництві дерев'яних будинків та беседок. Ми
          використовуємо тільки високоякісне дерево та професійне обладнання для
          виготовлення наших продуктів. Наші дерев'яні блоки можуть бути
          використані для будівництва стін будинків, а також для створення
          декоративних елементів та меблів. Ми здійснюємо будівництво будинків
          та беседок на замовлення, забезпечуючи високу якість робіт та
          своєчасну доставку готових проектів. Наша мета - надати клієнтам
          якісні та надійні рішення для будівництва з дерева.
        </p>
      </div>
    </div>
  </div>

  <a href="../#howitworks-section" class="smoothscroll arrow-down"
    ><span class="icon-arrow_downward"></span
  ></a>
</div>

main_app/templates/listining_section.html
<div class="site-section" id="listings-section">
  <div class="container">
    <div class="row g-0">
      <div class="col-md-2 order-1 order-md-2">
        <div class="mb-5">
          <h3 class="text-black mb-4 h5 font-family-2">Filter</h3>
          <form action="#">
            <div class="form-group">
              <div class="select-wrap">
                <span class="icon icon-keyboard_arrow_down"></span>
                <select class="form-control px-3">
                  <option value="">By Date</option>
                  <option value="">Trending</option>
                  <option value="">Best</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="select-wrap">
                <span class="icon icon-keyboard_arrow_down"></span>
                <select class="form-control px-3">
                  <option value="">1 Bath, 1 Bedroom</option>
                  <option value="">2 Bath, 2 Bedroom</option>
                  <option value="">3+ Bath, 3+ Bedroom</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="select-wrap">
                <span class="icon icon-keyboard_arrow_down"></span>
                <select class="form-control px-3">
                  <option value="">For Sale</option>
                  <option value="">For Rent</option>
                  <option value="">For Lease</option>
                </select>
              </div>
            </div>
          </form>
        </div>

        <div class="mb-5">
          <h3 class="text-black mb-4 h5 font-family-2">Filter by Price</h3>
          <div id="slider-range" class="border-primary"></div>
          <input
            type="text"
            name="text"
            id="amount"
            class="form-control border-0 pl-0 bg-white"
            disabled=""
          />
        </div>
      </div>
      <div class="glightbox col-md-5 order-2 order-md-1">
        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_1-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_2-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_3-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_4-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_5-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_1-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_2-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_3-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_4-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>

        <div class="property horizontal d-flex">
          <div class="mr-3 img-entry">
            <a href="property-single.html"
              ><img
                src="images/property_5-sm.jpg"
                alt="Image"
                class="img-fluid"
            /></a>
          </div>
          <div class="prop-details p-3">
            <div>
              <a href="property-single.html"
                ><strong class="price">$3,400,000</strong></a
              >
            </div>
            <div class="mb-2 d-flex justify-content-between">
              <span class="w border-r">6 beds</span>
              <span class="w border-r">4 baths</span>
              <span class="w">4,250 sqft.</span>
            </div>
            <div>480 12th, Unit 14, San Francisco, CA</div>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-9">
        <div class="custom-pagination text-center">
          <span>1</span>
          <a href="#">2</a>
          <a href="#">3</a>
          <span class="more-page">...</span>
          <a href="#">7</a>
        </div>
      </div>
    </div>
  </div>
</div>

main_app/templates/main_page.html
{% extends 'index.html' %} {% block main_content %}

    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">

      <div class="container">
        <div class="row align-items-center">

          <div class="col-6 col-xl-1">
            <h1 class="mb-0 site-logo m-0 p-0"><img src="../static/img/logo2.png" alt="WoodenHouse" width="180"></h1>
          </div>

          <div class="col-1 col-md-11 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right" role="navigation">

              <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                  {% if user.username %}
                <a href="{% url 'listings' %}" class="nav-link">Прайс</a>
                <a href="#properties-section" class="nav-link">Популярне</a>
                <a href="../#agents-section" class="nav-link">Персонал</a>
                <a href="../#about-section" class="nav-link">Про компанію</a>
                <a href="../#contact-section" class="nav-link">Контакти</a>
                <a class="nav-link" href="{% url 'office' %}">{{ user.username }} </a>
                {% if 'manager' in user.groups.all.values_list|join:","%}
                    <a href="{% url 'manager:reservation' %}" class="btn btn-primary text-black nav-link">Менеджер</a>
                {% endif %}
                <a href="{% url 'logout' %}" class="btn btn-primary text-black nav-link">Вийти</a>
                  {% else %}
                <a href="#properties-section" class="nav-link">Популярне</a>
                <a href="#agents-section" class="nav-link">Персонал</a>
                <a href="#about-section" class="nav-link">Про компанію</a>
                <a href="#news-section" class="nav-link">Новини</a>
                <a href="#contact-section" class="nav-link">Контакти</a>
                <a href="{% url 'login' %}" class="btn btn-primary text-black nav-link">Увійти</a>
                <a href="{% url 'registration' %}" class="btn btn-primary text-black nav-link" type="button">Реєстрація</a>
                  {% endif %}
              </ul>
            {% if 'manager' in user.groups.all.values_list|join:","%}
                <p class="col-md-12 text-right">Цей користувач належить до групи менеджерів.</p>
            {% endif %}
            </nav>
          </div>

          <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-black float-right"><span class="icon-menu h3"></span></a></div>

        </div>
      </div>

    </header>
<!-- home-section -->
{% include 'home_section.html' %}
<!-- end_home-section -->

<div class="py-5 bg-light site-section how-it-works" id="howitworks-section">
  <div class="container">
    <div class="row mb-5 justify-content-center">
      <div class="col-md-7 text-center">
        <h2 class="section-title mb-3">Як це працює!</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 text-center">
        <div class="pr-5">
          <span class="custom-icon flaticon-house text-primary"></span>
          <h3 class="text-dark">Знайди товар який вас цікавить.</h3>
          <p>Завітай у вкладку "Прайс", та вибери саме те що вам потрібно.</p>
        </div>
      </div>

      <div class="col-md-4 text-center">
        <div class="pr-5">
          <span class="custom-icon flaticon-coin text-primary"></span>
          <h3 class="text-dark">Подай заявку.</h3>
          <p>Залиш свою заявку у розділі "Контакти" і ми з вами зв'яжемось.</p>
        </div>
      </div>

      <div class="col-md-4 text-center">
        <div class="pr-5">
          <span class="custom-icon flaticon-home text-primary"></span>
          <h3 class="text-dark">Контакти.</h3>
          <p>Ви можете зателефонувати нам, наш менеджер надасть вам всю необхідну інформацію.</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% comment %}
<!-- listining_section -->
{% include 'listining_section.html' %}
<!-- end_listining_section -->
{% endcomment %}

<!-- properties-section -->
{% include 'properties.html' %}
<!-- end_properties-section -->

<!-- services-section -->
{#{% include 'services.html' %}#}
<!-- end_services-section -->

<!-- news-section -->
{% include 'news.html' %}
<!-- end_news-section -->

<!-- about-section -->
{% include 'about.html' %}
<!-- end_about-section -->

<!-- agents-section -->
{% include 'agents.html' %}
<!-- end_agents-section -->

<!-- map-section -->
{% include 'map_section.html' %}
<!-- end_map-section -->

<!-- contact-section -->
{% include 'contact.html' %}
<!-- end_contact-section -->

{% endblock %}

main_app/templates/map_section.html
<div class="row">
    <div class="col-md-12 text-center">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2118.2738987632224!2d24.320728269504965!3d50.848454817336155!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x472458d42e3cb047%3A0xfb326c3c454521cc!2z0JLQu9Cw0LTQuNC80LjRgCwg0JLQvtC70YvQvdGB0LrQsNGPINC-0LHQu9Cw0YHRgtGMLCA0NDcwMQ!5e0!3m2!1sru!2sua!4v1681155426439!5m2!1sru!2sua" width="1600" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>

main_app/templates/news.html
<section class="site-section" id="news-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-12 text-center">
        <h2 class="section-title mb-3">Новини &amp; Пропозиції &amp; Події</h2>
      </div>
    </div>

    <div class="row">
        {% for new in news %}
      <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
        <div class="h-entry">
          <a href="single.html"
            ><img src="{{ new.photo.url }}" alt="Image{{ new.title }}" class="img-fluid"
          /></a>
          <h2 class="font-size-regular text-dark">
            {{ new.message }}
          </h2>
          <div class="meta mb-4">
            {{ new.title }} <span class="mx-2">&bullet;</span>{{ new.date }}<span
              class="mx-2"
              >&bullet;</span
            >
            <a href="single.html">News</a>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
  </div>
</section>