SmollProdject/urls.py
from django.contrib import admin
from django.urls import path, include
from listings.views import listings_view
from main_app.views import main_view
from django.conf import settings
from django.conf.urls.static import static
from account.views import registration_view, login_view, logout_view
from office.views import office_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listings/', listings_view, name='listings'),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),
    path('office/', office_view, name='office'),
    path('', main_view, name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation

app_name = 'manager'

urlpatterns = [
	path('', reservation_list, name='reservation'),
	path('update/<int:pk>', update_reservation, name='update_reservation'),
]

office/models.py
from django.db import models

# Create your models here.

office/views.py
from django.shortcuts import render
from main_app.models import Reservation
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def office_view(request):
	# massages = Reservation.objects.filter(is_processed=False)
	return render(request, 'office_list.html', context={'reservation': 'No reservation'})

office/templates/office_list.html
{% extends 'index.html' %}
{% block main_content %}
    <div class="container">
        <div class="row align-items-center">

          <div class="col-12 col-xl-2">
            <a href="{% url 'main' %}" class="mb-0 site-logo m-0 p-0"><img src="../static/img/logo2.png" alt="WoodenHous" width="220"></a>
          </div>
        </div>
    </div>

<section class="site-section bg-light bg-image" id="contact-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-1">
        <div class="col-12 text-center">
        <!-- <h3 class="section-sub-title">Get</h3> -->
        <h2 class="section-title mb-3">Ваш кабінет!</h2>
      </div>
      </div>
    </div>
  </div>
</section>
{#    {% for item in reservation %}#}
{#          <div class="col-md-11 ml-5 input-group pb-1">#}
  {#      <div class="form-control text-secondary col-4">{{ item.name }}</div>#}
  {#     <div class="form-control text-secondary  col-4">{{ item.email }}</div>#}
  {#     <div class="form-control text-secondary  col-4">{{ item.phone }}</div>#}
  {#   <a class="input-group-append" href="{% url 'manager:update_reservation' pk=item.pk %}">#}
    {#     <button type="button" class="btn btn-primary text-black pb-1">Підтвердити</button>#}
    {#   </a>#}
      {#   </div>#}
        {#      </div>#}
          {#   {% endfor %}#}
    <br>
{% endblock %}